document.addEventListener("DOMContentLoaded", () => {
	// create dropdown as part of form to represent priority of task
	const dropdown = document.createElement("select");
	dropdown.name = "priority";
	dropdown.id = "priority";
	//create options
	const highOption = document.createElement("option");
	highOption.innerText = "high";
	highOption.value = "high";
	const medOption = document.createElement("option");
	medOption.innerText = "med";
	medOption.value = "med";
	const lowOption = document.createElement("option");
	lowOption.innerText = "low";
	lowOption.value = "low";
	//append options to dropdown
	dropdown.append(highOption);
	dropdown.append(medOption);
	dropdown.append(lowOption);
	// have dropdown options for high, med, low

	// capture the necessary nodes that we need for our events and for appending
	const taskForm = document.getElementById("create-task-form");
	const taskList = document.getElementById("tasks");

	taskForm.append(dropdown);

	//create a new input field for duration
	const durationInput = document.createElement("input");
	durationInput.id = "duration";
	durationInput.name = "duration";
	durationInput.placeholder = "duration";
	// append the new input field to the existing form (taskForm)
	taskForm.append(durationInput);

	// create our event listener
	// e is a receipt of the current event transaction (including a timestamp)
	// e is automatically generated by addEventListener
	// e is an object that contains, among other things, the element that triggered the event (e.target)
	taskForm.addEventListener("submit", (e) => {
		e.preventDefault();
		//e.target: is the form itself (generally the element that triggered the event)
		//["new-task-description"]: is getting the specific input field of the form (if you look in index.html the input has a "name=new-task-description")
		//.value is a property of the new-task-description input field that contains what the user typed
		let newTask = e.target["new-task-description"].value;
		let newDuration = e.target.duration.value;
		// create delete button
		let deleteButton = document.createElement("button");
		let taskLi = document.createElement("li");
		//set taskLi text color based on priority
		let taskPriority = e.target.priority.value;
		if (taskPriority === "high") {
			//make text red
			taskLi.style.color = "red";
		} else if (taskPriority === "med") {
			//make text orange
			taskLi.style.color = "orange";
		} else {
			//make text green
			taskLi.style.color = "green";
		}

		taskLi.textContent = `${newTask} for ${newDuration} minutes`;
		deleteButton.textContent = "Delete";
		taskList.append(taskLi);
		// append delete button to task list item
		taskLi.append(deleteButton);
		// create event listener on delete button

		//each instance of a deleteButton has its own instance of the click event
		deleteButton.addEventListener("click", (e) => {
			// on event listener, remove task list item (the entire li)
			taskLi.remove();
		});
	});
});


